javax:
  sql:
    DataSource:
      backoffice:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        dataSource:
          url: jdbc:postgresql://localhost:5432/smartbar
          user: postgres
          password: postgres
security:
  providers:
    - http-basic-auth:
        realm: smartbar
        users:
          - login: admin
            password: ${GCM=S4Li4AF4O7yL7r53crTqpjeLGsXTJjoHDn09uEAbNLkrsQ8Ow+07u6exk2ew0I+maA==}
            roles: ["admin"]
          - login: bob
            password: ${GCM=jNWC8EGPh/xi9nfr6GBAdz4SD3BYZLTRds0ybRXuwrBqbZCFj3EFuf7ZpQuMqNw=}
            roles: ["user"]